/**
 * Meta Data Controller - Provides static/API data for dropdowns
 * Education, Occupation, Religion options
 */

/**
 * Get Education Options
 * GET /api/meta/education
 */
export const getEducationOptions = async (req, res, next) => {
  try {
    // Common education levels/degrees in India
    const educationOptions = [
      { value: '10th', label: '10th / SSC' },
      { value: '12th', label: '12th / HSC' },
      { value: 'diploma', label: 'Diploma' },
      { value: 'graduate', label: 'Graduate / Bachelor\'s Degree' },
      { value: 'btech', label: 'B.Tech / B.E.' },
      { value: 'mba', label: 'MBA' },
      { value: 'mtech', label: 'M.Tech / M.E.' },
      { value: 'mca', label: 'MCA' },
      { value: 'bca', label: 'BCA' },
      { value: 'bcom', label: 'B.Com' },
      { value: 'mcom', label: 'M.Com' },
      { value: 'ba', label: 'B.A.' },
      { value: 'ma', label: 'M.A.' },
      { value: 'bsc', label: 'B.Sc' },
      { value: 'msc', label: 'M.Sc' },
      { value: 'bba', label: 'BBA' },
      { value: 'mbb', label: 'MBB / MBBS' },
      { value: 'md', label: 'MD / MS' },
      { value: 'phd', label: 'Ph.D' },
      { value: 'ca', label: 'CA' },
      { value: 'cs', label: 'CS' },
      { value: 'icwa', label: 'ICWA' },
      { value: 'llb', label: 'LLB' },
      { value: 'llm', label: 'LLM' },
      { value: 'other', label: 'Other' },
    ];

    res.json({
      status: true,
      message: 'Education options retrieved successfully',
      data: educationOptions
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get Occupation Options
 * GET /api/meta/occupation
 */
export const getOccupationOptions = async (req, res, next) => {
  try {
    // Common occupations in India
    const occupationOptions = [
      { value: 'software-engineer', label: 'Software Engineer / IT Professional' },
      { value: 'doctor', label: 'Doctor / Physician' },
      { value: 'engineer', label: 'Engineer (Civil/Mechanical/Electrical)' },
      { value: 'teacher', label: 'Teacher / Professor' },
      { value: 'lawyer', label: 'Lawyer / Advocate' },
      { value: 'ca', label: 'CA / Chartered Accountant' },
      { value: 'cs', label: 'CS / Company Secretary' },
      { value: 'business', label: 'Business / Entrepreneur' },
      { value: 'government', label: 'Government Employee' },
      { value: 'banking', label: 'Banking / Finance Professional' },
      { value: 'marketing', label: 'Marketing / Sales Professional' },
      { value: 'hr', label: 'HR / Human Resources' },
      { value: 'nurse', label: 'Nurse / Healthcare Professional' },
      { value: 'pharmacist', label: 'Pharmacist' },
      { value: 'architect', label: 'Architect' },
      { value: 'designer', label: 'Designer (Graphic/Interior/Fashion)' },
      { value: 'journalist', label: 'Journalist / Media Professional' },
      { value: 'scientist', label: 'Scientist / Researcher' },
      { value: 'pilot', label: 'Pilot / Aviation' },
      { value: 'military', label: 'Defense / Military' },
      { value: 'policeman', label: 'Police / Security' },
      { value: 'artist', label: 'Artist / Creative Professional' },
      { value: 'consultant', label: 'Consultant' },
      { value: 'manager', label: 'Manager / Executive' },
      { value: 'dentist', label: 'Dentist' },
      { value: 'veterinarian', label: 'Veterinarian' },
      { value: 'accountant', label: 'Accountant' },
      { value: 'chef', label: 'Chef / Cook' },
      { value: 'homemaker', label: 'Home Maker' },
      { value: 'student', label: 'Student' },
      { value: 'retired', label: 'Retired' },
      { value: 'data-scientist', label: 'Data Scientist / Analyst' },
      { value: 'product-manager', label: 'Product Manager' },
      { value: 'project-manager', label: 'Project Manager' },
      { value: 'operations', label: 'Operations Manager' },
      { value: 'supply-chain', label: 'Supply Chain / Logistics' },
      { value: 'quality-assurance', label: 'Quality Assurance / Testing' },
      { value: 'network-engineer', label: 'Network Engineer' },
      { value: 'cybersecurity', label: 'Cybersecurity Professional' },
      { value: 'ui-ux-designer', label: 'UI/UX Designer' },
      { value: 'web-developer', label: 'Web Developer' },
      { value: 'mobile-developer', label: 'Mobile App Developer' },
      { value: 'devops', label: 'DevOps Engineer' },
      { value: 'cloud-engineer', label: 'Cloud Engineer' },
      { value: 'ai-ml-engineer', label: 'AI/ML Engineer' },
      { value: 'surgeon', label: 'Surgeon' },
      { value: 'gynecologist', label: 'Gynecologist' },
      { value: 'pediatrician', label: 'Pediatrician' },
      { value: 'cardiologist', label: 'Cardiologist' },
      { value: 'dermatologist', label: 'Dermatologist' },
      { value: 'ophthalmologist', label: 'Ophthalmologist' },
      { value: 'orthopedic', label: 'Orthopedic Surgeon' },
      { value: 'psychiatrist', label: 'Psychiatrist' },
      { value: 'physiotherapist', label: 'Physiotherapist' },
      { value: 'nutritionist', label: 'Nutritionist / Dietitian' },
      { value: 'yoga-instructor', label: 'Yoga Instructor' },
      { value: 'fitness-trainer', label: 'Fitness Trainer' },
      { value: 'civil-engineer', label: 'Civil Engineer' },
      { value: 'mechanical-engineer', label: 'Mechanical Engineer' },
      { value: 'electrical-engineer', label: 'Electrical Engineer' },
      { value: 'electronics-engineer', label: 'Electronics Engineer' },
      { value: 'chemical-engineer', label: 'Chemical Engineer' },
      { value: 'aerospace-engineer', label: 'Aerospace Engineer' },
      { value: 'automotive-engineer', label: 'Automotive Engineer' },
      { value: 'biomedical-engineer', label: 'Biomedical Engineer' },
      { value: 'environmental-engineer', label: 'Environmental Engineer' },
      { value: 'industrial-engineer', label: 'Industrial Engineer' },
      { value: 'marine-engineer', label: 'Marine Engineer' },
      { value: 'mining-engineer', label: 'Mining Engineer' },
      { value: 'petroleum-engineer', label: 'Petroleum Engineer' },
      { value: 'structural-engineer', label: 'Structural Engineer' },
      { value: 'professor', label: 'Professor / Lecturer' },
      { value: 'principal', label: 'Principal / School Head' },
      { value: 'counselor', label: 'Counselor / Psychologist' },
      { value: 'librarian', label: 'Librarian' },
      { value: 'judge', label: 'Judge' },
      { value: 'notary', label: 'Notary Public' },
      { value: 'legal-advisor', label: 'Legal Advisor' },
      { value: 'company-secretary', label: 'Company Secretary' },
      { value: 'cost-accountant', label: 'Cost Accountant' },
      { value: 'financial-advisor', label: 'Financial Advisor' },
      { value: 'investment-banker', label: 'Investment Banker' },
      { value: 'stock-broker', label: 'Stock Broker' },
      { value: 'insurance-agent', label: 'Insurance Agent' },
      { value: 'real-estate-agent', label: 'Real Estate Agent' },
      { value: 'property-consultant', label: 'Property Consultant' },
      { value: 'interior-designer', label: 'Interior Designer' },
      { value: 'fashion-designer', label: 'Fashion Designer' },
      { value: 'jewelry-designer', label: 'Jewelry Designer' },
      { value: 'graphic-designer', label: 'Graphic Designer' },
      { value: 'animator', label: 'Animator' },
      { value: 'video-editor', label: 'Video Editor' },
      { value: 'photographer', label: 'Photographer' },
      { value: 'cinematographer', label: 'Cinematographer' },
      { value: 'musician', label: 'Musician / Singer' },
      { value: 'dancer', label: 'Dancer' },
      { value: 'actor', label: 'Actor / Actress' },
      { value: 'model', label: 'Model' },
      { value: 'sports-person', label: 'Sports Person / Athlete' },
      { value: 'coach', label: 'Coach / Trainer' },
      { value: 'social-worker', label: 'Social Worker' },
      { value: 'ngo-worker', label: 'NGO Worker' },
      { value: 'politician', label: 'Politician' },
      { value: 'bureaucrat', label: 'Bureaucrat / IAS / IPS' },
      { value: 'diplomat', label: 'Diplomat' },
      { value: 'translator', label: 'Translator / Interpreter' },
      { value: 'writer', label: 'Writer / Author' },
      { value: 'poet', label: 'Poet' },
      { value: 'blogger', label: 'Blogger / Content Creator' },
      { value: 'influencer', label: 'Social Media Influencer' },
      { value: 'youtuber', label: 'YouTuber' },
      { value: 'podcaster', label: 'Podcaster' },
      { value: 'event-manager', label: 'Event Manager' },
      { value: 'wedding-planner', label: 'Wedding Planner' },
      { value: 'caterer', label: 'Caterer' },
      { value: 'hotel-manager', label: 'Hotel Manager' },
      { value: 'restaurant-owner', label: 'Restaurant Owner' },
      { value: 'travel-agent', label: 'Travel Agent' },
      { value: 'tour-guide', label: 'Tour Guide' },
      { value: 'flight-attendant', label: 'Flight Attendant' },
      { value: 'air-hostess', label: 'Air Hostess' },
      { value: 'ground-staff', label: 'Airport Ground Staff' },
      { value: 'air-traffic-controller', label: 'Air Traffic Controller' },
      { value: 'ship-captain', label: 'Ship Captain' },
      { value: 'sailor', label: 'Sailor / Seafarer' },
      { value: 'railway-employee', label: 'Railway Employee' },
      { value: 'bus-driver', label: 'Bus Driver' },
      { value: 'taxi-driver', label: 'Taxi Driver' },
      { value: 'truck-driver', label: 'Truck Driver' },
      { value: 'mechanic', label: 'Mechanic' },
      { value: 'electrician', label: 'Electrician' },
      { value: 'plumber', label: 'Plumber' },
      { value: 'carpenter', label: 'Carpenter' },
      { value: 'painter', label: 'Painter' },
      { value: 'mason', label: 'Mason' },
      { value: 'welder', label: 'Welder' },
      { value: 'farmer', label: 'Farmer / Agriculturist' },
      { value: 'veterinary-doctor', label: 'Veterinary Doctor' },
      { value: 'agricultural-engineer', label: 'Agricultural Engineer' },
      { value: 'forest-officer', label: 'Forest Officer' },
      { value: 'wildlife-conservationist', label: 'Wildlife Conservationist' },
      { value: 'fisherman', label: 'Fisherman' },
      { value: 'miner', label: 'Miner' },
      { value: 'construction-worker', label: 'Construction Worker' },
      { value: 'factory-worker', label: 'Factory Worker' },
      { value: 'warehouse-worker', label: 'Warehouse Worker' },
      { value: 'security-guard', label: 'Security Guard' },
      { value: 'housekeeper', label: 'Housekeeper / Maid' },
      { value: 'cook', label: 'Cook' },
      { value: 'waiter', label: 'Waiter / Server' },
      { value: 'bartender', label: 'Bartender' },
      { value: 'receptionist', label: 'Receptionist' },
      { value: 'secretary', label: 'Secretary / Personal Assistant' },
      { value: 'clerk', label: 'Clerk' },
      { value: 'cashier', label: 'Cashier' },
      { value: 'sales-associate', label: 'Sales Associate' },
      { value: 'customer-service', label: 'Customer Service Representative' },
      { value: 'call-center', label: 'Call Center Executive' },
      { value: 'telemarketer', label: 'Telemarketer' },
      { value: 'delivery-person', label: 'Delivery Person' },
      { value: 'courier', label: 'Courier' },
      { value: 'postman', label: 'Postman' },
      { value: 'newspaper-vendor', label: 'Newspaper Vendor' },
      { value: 'milkman', label: 'Milkman' },
      { value: 'vegetable-vendor', label: 'Vegetable Vendor' },
      { value: 'shopkeeper', label: 'Shopkeeper / Retailer' },
      { value: 'wholesaler', label: 'Wholesaler' },
      { value: 'distributor', label: 'Distributor' },
      { value: 'importer', label: 'Importer' },
      { value: 'exporter', label: 'Exporter' },
      { value: 'trader', label: 'Trader' },
      { value: 'merchant', label: 'Merchant' },
      { value: 'manufacturer', label: 'Manufacturer' },
      { value: 'contractor', label: 'Contractor' },
      { value: 'builder', label: 'Builder / Developer' },
      { value: 'architectural-drafter', label: 'Architectural Drafter' },
      { value: 'surveyor', label: 'Surveyor' },
      { value: 'landscape-architect', label: 'Landscape Architect' },
      { value: 'urban-planner', label: 'Urban Planner' },
      { value: 'geologist', label: 'Geologist' },
      { value: 'meteorologist', label: 'Meteorologist' },
      { value: 'oceanographer', label: 'Oceanographer' },
      { value: 'astronomer', label: 'Astronomer' },
      { value: 'physicist', label: 'Physicist' },
      { value: 'chemist', label: 'Chemist' },
      { value: 'biologist', label: 'Biologist' },
      { value: 'microbiologist', label: 'Microbiologist' },
      { value: 'biotechnologist', label: 'Biotechnologist' },
      { value: 'geneticist', label: 'Geneticist' },
      { value: 'pharmacologist', label: 'Pharmacologist' },
      { value: 'toxicologist', label: 'Toxicologist' },
      { value: 'epidemiologist', label: 'Epidemiologist' },
      { value: 'public-health', label: 'Public Health Professional' },
      { value: 'health-inspector', label: 'Health Inspector' },
      { value: 'sanitation-worker', label: 'Sanitation Worker' },
      { value: 'waste-management', label: 'Waste Management Professional' },
      { value: 'environmental-scientist', label: 'Environmental Scientist' },
      { value: 'conservationist', label: 'Conservationist' },
      { value: 'renewable-energy', label: 'Renewable Energy Professional' },
      { value: 'solar-engineer', label: 'Solar Engineer' },
      { value: 'wind-engineer', label: 'Wind Energy Engineer' },
      { value: 'nuclear-engineer', label: 'Nuclear Engineer' },
      { value: 'power-engineer', label: 'Power Engineer' },
      { value: 'telecom-engineer', label: 'Telecom Engineer' },
      { value: 'broadcast-engineer', label: 'Broadcast Engineer' },
      { value: 'sound-engineer', label: 'Sound Engineer' },
      { value: 'lighting-engineer', label: 'Lighting Engineer' },
      { value: 'stage-manager', label: 'Stage Manager' },
      { value: 'production-manager', label: 'Production Manager' },
      { value: 'director', label: 'Director' },
      { value: 'producer', label: 'Producer' },
      { value: 'screenwriter', label: 'Screenwriter' },
      { value: 'editor', label: 'Editor' },
      { value: 'makeup-artist', label: 'Makeup Artist' },
      { value: 'hairstylist', label: 'Hair Stylist' },
      { value: 'beautician', label: 'Beautician' },
      { value: 'spa-therapist', label: 'Spa Therapist' },
      { value: 'massage-therapist', label: 'Massage Therapist' },
      { value: 'acupuncturist', label: 'Acupuncturist' },
      { value: 'chiropractor', label: 'Chiropractor' },
      { value: 'homeopath', label: 'Homeopath' },
      { value: 'ayurvedic-doctor', label: 'Ayurvedic Doctor' },
      { value: 'unani-doctor', label: 'Unani Doctor' },
      { value: 'siddha-doctor', label: 'Siddha Doctor' },
      { value: 'naturopath', label: 'Naturopath' },
      { value: 'acupressure', label: 'Acupressure Therapist' },
      { value: 'reflexologist', label: 'Reflexologist' },
      { value: 'aromatherapist', label: 'Aromatherapist' },
      { value: 'reiki-healer', label: 'Reiki Healer' },
      { value: 'astrologer', label: 'Astrologer' },
      { value: 'palmist', label: 'Palmist' },
      { value: 'numerologist', label: 'Numerologist' },
      { value: 'vastu-consultant', label: 'Vastu Consultant' },
      { value: 'feng-shui', label: 'Feng Shui Consultant' },
      { value: 'priest', label: 'Priest / Pujari' },
      { value: 'imam', label: 'Imam' },
      { value: 'rabbi', label: 'Rabbi' },
      { value: 'monk', label: 'Monk' },
      { value: 'nun', label: 'Nun' },
      { value: 'missionary', label: 'Missionary' },
      { value: 'evangelist', label: 'Evangelist' },
      { value: 'theologian', label: 'Theologian' },
      { value: 'religious-teacher', label: 'Religious Teacher' },
      { value: 'quran-teacher', label: 'Quran Teacher' },
      { value: 'vedic-teacher', label: 'Vedic Teacher' },
      { value: 'sanskrit-teacher', label: 'Sanskrit Teacher' },
      { value: 'language-teacher', label: 'Language Teacher' },
      { value: 'music-teacher', label: 'Music Teacher' },
      { value: 'dance-teacher', label: 'Dance Teacher' },
      { value: 'art-teacher', label: 'Art Teacher' },
      { value: 'sports-teacher', label: 'Sports Teacher' },
      { value: 'coaching-center', label: 'Coaching Center Owner' },
      { value: 'tuition-teacher', label: 'Tuition Teacher' },
      { value: 'online-tutor', label: 'Online Tutor' },
      { value: 'exam-preparation', label: 'Exam Preparation Coach' },
      { value: 'career-counselor', label: 'Career Counselor' },
      { value: 'admission-consultant', label: 'Admission Consultant' },
      { value: 'study-abroad', label: 'Study Abroad Consultant' },
      { value: 'visa-consultant', label: 'Visa Consultant' },
      { value: 'immigration-consultant', label: 'Immigration Consultant' },
      { value: 'recruitment-consultant', label: 'Recruitment Consultant' },
      { value: 'headhunter', label: 'Headhunter' },
      { value: 'talent-acquisition', label: 'Talent Acquisition Specialist' },
      { value: 'compensation-analyst', label: 'Compensation Analyst' },
      { value: 'benefits-administrator', label: 'Benefits Administrator' },
      { value: 'payroll-specialist', label: 'Payroll Specialist' },
      { value: 'training-specialist', label: 'Training Specialist' },
      { value: 'organizational-development', label: 'Organizational Development Specialist' },
      { value: 'employee-relations', label: 'Employee Relations Specialist' },
      { value: 'labor-lawyer', label: 'Labor Lawyer' },
      { value: 'employment-lawyer', label: 'Employment Lawyer' },
      { value: 'corporate-lawyer', label: 'Corporate Lawyer' },
      { value: 'tax-lawyer', label: 'Tax Lawyer' },
      { value: 'patent-lawyer', label: 'Patent Lawyer' },
      { value: 'intellectual-property', label: 'Intellectual Property Lawyer' },
      { value: 'criminal-lawyer', label: 'Criminal Lawyer' },
      { value: 'family-lawyer', label: 'Family Lawyer' },
      { value: 'divorce-lawyer', label: 'Divorce Lawyer' },
      { value: 'immigration-lawyer', label: 'Immigration Lawyer' },
      { value: 'real-estate-lawyer', label: 'Real Estate Lawyer' },
      { value: 'property-lawyer', label: 'Property Lawyer' },
      { value: 'construction-lawyer', label: 'Construction Lawyer' },
      { value: 'environmental-lawyer', label: 'Environmental Lawyer' },
      { value: 'media-lawyer', label: 'Media Lawyer' },
      { value: 'entertainment-lawyer', label: 'Entertainment Lawyer' },
      { value: 'sports-lawyer', label: 'Sports Lawyer' },
      { value: 'aviation-lawyer', label: 'Aviation Lawyer' },
      { value: 'maritime-lawyer', label: 'Maritime Lawyer' },
      { value: 'insurance-lawyer', label: 'Insurance Lawyer' },
      { value: 'banking-lawyer', label: 'Banking Lawyer' },
      { value: 'securities-lawyer', label: 'Securities Lawyer' },
      { value: 'antitrust-lawyer', label: 'Antitrust Lawyer' },
      { value: 'regulatory-lawyer', label: 'Regulatory Lawyer' },
      { value: 'compliance-officer', label: 'Compliance Officer' },
      { value: 'risk-manager', label: 'Risk Manager' },
      { value: 'auditor', label: 'Auditor' },
      { value: 'internal-auditor', label: 'Internal Auditor' },
      { value: 'external-auditor', label: 'External Auditor' },
      { value: 'tax-consultant', label: 'Tax Consultant' },
      { value: 'gst-consultant', label: 'GST Consultant' },
      { value: 'income-tax', label: 'Income Tax Consultant' },
      { value: 'sales-tax', label: 'Sales Tax Consultant' },
      { value: 'customs-officer', label: 'Customs Officer' },
      { value: 'excise-officer', label: 'Excise Officer' },
      { value: 'tax-inspector', label: 'Tax Inspector' },
      { value: 'assistant-commissioner', label: 'Assistant Commissioner' },
      { value: 'deputy-commissioner', label: 'Deputy Commissioner' },
      { value: 'joint-commissioner', label: 'Joint Commissioner' },
      { value: 'additional-commissioner', label: 'Additional Commissioner' },
      { value: 'commissioner', label: 'Commissioner' },
      { value: 'secretary', label: 'Secretary' },
      { value: 'joint-secretary', label: 'Joint Secretary' },
      { value: 'additional-secretary', label: 'Additional Secretary' },
      { value: 'principal-secretary', label: 'Principal Secretary' },
      { value: 'chief-secretary', label: 'Chief Secretary' },
      { value: 'cabinet-secretary', label: 'Cabinet Secretary' },
      { value: 'governor', label: 'Governor' },
      { value: 'lieutenant-governor', label: 'Lieutenant Governor' },
      { value: 'chief-minister', label: 'Chief Minister' },
      { value: 'deputy-chief-minister', label: 'Deputy Chief Minister' },
      { value: 'minister', label: 'Minister' },
      { value: 'state-minister', label: 'State Minister' },
      { value: 'union-minister', label: 'Union Minister' },
      { value: 'prime-minister', label: 'Prime Minister' },
      { value: 'president', label: 'President' },
      { value: 'vice-president', label: 'Vice President' },
      { value: 'speaker', label: 'Speaker' },
      { value: 'deputy-speaker', label: 'Deputy Speaker' },
      { value: 'member-parliament', label: 'Member of Parliament (MP)' },
      { value: 'member-assembly', label: 'Member of Legislative Assembly (MLA)' },
      { value: 'member-council', label: 'Member of Legislative Council (MLC)' },
      { value: 'mayor', label: 'Mayor' },
      { value: 'deputy-mayor', label: 'Deputy Mayor' },
      { value: 'corporator', label: 'Corporator' },
      { value: 'councilor', label: 'Councilor' },
      { value: 'sarpanch', label: 'Sarpanch' },
      { value: 'panchayat-member', label: 'Panchayat Member' },
      { value: 'block-development-officer', label: 'Block Development Officer (BDO)' },
      { value: 'tehsildar', label: 'Tehsildar' },
      { value: 'naib-tehsildar', label: 'Naib Tehsildar' },
      { value: 'patwari', label: 'Patwari' },
      { value: 'revenue-officer', label: 'Revenue Officer' },
      { value: 'sub-registrar', label: 'Sub-Registrar' },
      { value: 'registrar', label: 'Registrar' },
      { value: 'district-collector', label: 'District Collector' },
      { value: 'district-magistrate', label: 'District Magistrate (DM)' },
      { value: 'sub-divisional-magistrate', label: 'Sub-Divisional Magistrate (SDM)' },
      { value: 'executive-magistrate', label: 'Executive Magistrate' },
      { value: 'judicial-magistrate', label: 'Judicial Magistrate' },
      { value: 'chief-judicial-magistrate', label: 'Chief Judicial Magistrate' },
      { value: 'session-judge', label: 'Session Judge' },
      { value: 'district-judge', label: 'District Judge' },
      { value: 'additional-district-judge', label: 'Additional District Judge' },
      { value: 'high-court-judge', label: 'High Court Judge' },
      { value: 'chief-justice', label: 'Chief Justice' },
      { value: 'supreme-court-judge', label: 'Supreme Court Judge' },
      { value: 'chief-justice-india', label: 'Chief Justice of India' },
      { value: 'advocate-general', label: 'Advocate General' },
      { value: 'solicitor-general', label: 'Solicitor General' },
      { value: 'additional-solicitor-general', label: 'Additional Solicitor General' },
      { value: 'attorney-general', label: 'Attorney General' },
      { value: 'public-prosecutor', label: 'Public Prosecutor' },
      { value: 'government-pleader', label: 'Government Pleader' },
      { value: 'notary', label: 'Notary' },
      { value: 'oath-commissioner', label: 'Oath Commissioner' },
      { value: 'document-writer', label: 'Document Writer' },
      { value: 'stamp-vendor', label: 'Stamp Vendor' },
      { value: 'court-clerk', label: 'Court Clerk' },
      { value: 'bailiff', label: 'Bailiff' },
      { value: 'process-server', label: 'Process Server' },
      { value: 'court-reporter', label: 'Court Reporter' },
      { value: 'stenographer', label: 'Stenographer' },
      { value: 'typist', label: 'Typist' },
      { value: 'data-entry', label: 'Data Entry Operator' },
      { value: 'computer-operator', label: 'Computer Operator' },
      { value: 'office-assistant', label: 'Office Assistant' },
      { value: 'peon', label: 'Peon' },
      { value: 'watchman', label: 'Watchman' },
      { value: 'sweeper', label: 'Sweeper' },
      { value: 'gardener', label: 'Gardener' },
      { value: 'caretaker', label: 'Caretaker' },
      { value: 'maintenance-worker', label: 'Maintenance Worker' },
      { value: 'janitor', label: 'Janitor' },
      { value: 'cleaner', label: 'Cleaner' },
      { value: 'sanitation-worker', label: 'Sanitation Worker' },
      { value: 'sewage-worker', label: 'Sewage Worker' },
      { value: 'drain-cleaner', label: 'Drain Cleaner' },
      { value: 'garbage-collector', label: 'Garbage Collector' },
      { value: 'rag-picker', label: 'Rag Picker' },
      { value: 'scrap-dealer', label: 'Scrap Dealer' },
      { value: 'recycler', label: 'Recycler' },
      { value: 'waste-picker', label: 'Waste Picker' },
      { value: 'other', label: 'Other' },
    ];

    res.json({
      status: true,
      message: 'Occupation options retrieved successfully',
      data: occupationOptions
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get Religion Options
 * GET /api/meta/religion
 */
export const getReligionOptions = async (req, res, next) => {
  try {
    // Common religions in India
    const religionOptions = [
      { value: 'hindu', label: 'Hindu' },
      { value: 'muslim', label: 'Muslim / Islam' },
      { value: 'christian', label: 'Christian' },
      { value: 'sikh', label: 'Sikh' },
      { value: 'jain', label: 'Jain' },
      { value: 'buddhist', label: 'Buddhist' },
      { value: 'parsi', label: 'Parsi / Zoroastrian' },
      { value: 'jewish', label: 'Jewish' },
      { value: 'bahai', label: 'Bahá\'í' },
      { value: 'other', label: 'Other' },
    ];

    res.json({
      status: true,
      message: 'Religion options retrieved successfully',
      data: religionOptions
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get Salary Range Options
 * GET /api/meta/salary
 * Returns salary ranges from 3L to 50L in 3L intervals
 * Format: Less than 3L, 3-6L, 6-9L, 9-12L, ..., 45-48L, 48-50L, 50L+
 */
export const getSalaryOptions = async (req, res, next) => {
  try {
    const salaryOptions = [];
    
    // Add "Less than 3L" option
    salaryOptions.push({
      value: 0,
      label: 'Less than ₹3L',
      min: 0,
      max: 299999,
    });
    
    // Generate salary ranges: 3-6L, 6-9L, 9-12L, ..., 45-48L, 48-50L
    for (let i = 3; i < 50; i += 3) {
      const nextValue = Math.min(i + 3, 50); // Cap at 50L
      
      if (nextValue === 50) {
        // Special case: 48-50L range
        salaryOptions.push({
          value: i * 100000,
          label: `₹${i}L - ₹${nextValue}L`,
          min: i * 100000,
          max: nextValue * 100000,
        });
      } else {
        salaryOptions.push({
          value: i * 100000,
          label: `₹${i}L - ₹${nextValue}L`,
          min: i * 100000,
          max: (nextValue * 100000) - 1, // Up to but not including next range
        });
      }
    }
    
    // Add "50L+" option
    salaryOptions.push({
      value: 5000000,
      label: '₹50L+',
      min: 5000000,
      max: null, // No upper limit
    });

    res.json({
      status: true,
      message: 'Salary options retrieved successfully',
      data: salaryOptions
    });
  } catch (error) {
    next(error);
  }
};

